### ISSUE TITLE
Full address shown instead of just city/country

### ISSUE THREAD

**Issue by erikmartin29** [WWDCScholars/web-app#3]
Despite only providing a city/country on the sign-up form, the site shows a full street address, as shown below:
<img width="300" alt="Screen Shot 2019-05-23 at 9 13 28 PM" src="https://user-images.githubusercontent.com/10319727/58302403-bb783480-7d9f-11e9-8499-dd51ccebdc64.png">

It used to work as intended, with only the city/country shown, but recently it has been displaying the entire street address (note that this isn't my exact address)

**Comment by moritzsternemann** [comment]
We use a best fit search in the reverse geocoder results using some metadata of the results. Feel free to suggest improvements / open a PR. You can find the implementation here: https://github.com/WWDCScholars/web-app/blob/48d6b79f3a5a09acc2384519a487f2832ae8c849/pages/s/_id.vue#L290

**Comment by DrBeta** [comment]
So, that is not @erikmartin29's real address, but where Apple Maps would take you?
